### ISSUE TITLE
UNK residues

### ISSUE THREAD

**Issue by AntoniyaAleksandrova** [rcsb/symmetry#114]
When there is a UNK residue in the protein structure (i.e. the residue is denoted as an "ATOM" entry in the pdb of the same chain as the rest of the protein), CE-Symm seems to treat it as non-existent and the produced FASTA alignments do not reflect its presence in the sequence. This can be somewhat confusing from a user's perspective. Since from what I understand only the position of the CA atom seems to matter for symmetry detection, is there a specific reason UNK residues are treated as non-existent and can they be added in?

**Comment by sbliven** [comment]
Do you have an example structure?

I don't know off-hand all the reasons UNK might be assigned, and whether there might be other cases where including them would be problematic.

**Comment by AntoniyaAleksandrova** [comment]
Hi Spencer, sorry for the delay in responding. For example, 6o84 has UNK residue entries in chain A and chain B. These entries start with "ATOM" and hence are considered part of the protein chain, even though the resolution might not be good enough to identify the specific amino acid. There are also cases where whole chains are represented with UNK residues - for example, chain X in 2axt. In the PDB sequence from the API, as well as other alignment software, these residues are often denoted with "X". Does this help?

**Comment by sbliven** [comment]
Looks like this was fixed upstream. CE-Symm 2.3.0 now aligns UNK residues without problem. 6o84.A:
<img width="1106" alt="Screenshot 2024-09-11 at 21 22 39" src="https://github.com/user-attachments/assets/67880ac1-d222-4c76-9121-59e43e7f5fae">
