### ISSUE TITLE
Improve CEsymm visualisation

### ISSUE THREAD

**Issue by andreasprlic** [rcsb/symmetry#36]
I feel the CEsymm visualisation is not clear enough. i wonder if the default view should be a single chain with the symmetric parts colored differently, rather than two chains that are superimposed.

**Comment by lafita** [comment]
In #49 a specific SymmetryGUI has been created for displaying the CEsymm results. A single chain of the protein is displayed with each symmetric part colored differently, and the option to see the self-alignment with one rotation is also available (the previous default view). 
As additional options a multiple alignment of the subunits and the alignment of two superimposed subunits can be shown under the "Symmetry" menu of the Jmol Frame, but they are still in development.

As Spencer said, the coloring and identification of the subunits depends entirely on the refinement method (on the goodness of the method), which can be chosen in the parameters.

As an example this is how the visualization looks now (for a very clear symmetric protein, 1U6D):

![1u6d_coloring](https://cloud.githubusercontent.com/assets/11161522/7176515/68dac922-e41f-11e4-96dc-0c202397984a.png)

**Comment by lafita** [comment]
New symmetry visualization options in Jmol using a multiple alignment: bcc593a

![multiple_3fold](https://cloud.githubusercontent.com/assets/11161522/7370124/0c9e794a-edb8-11e4-8835-42ca5cd1cd43.png)

**Comment by andreasprlic** [comment]
Very nice!



-- 
-----------------------------------------------------------------------
Dr. Andreas Prlic
RCSB PDB Protein Data Bank
Technical & Scientific Team Lead
University of California, San Diego

Editor Software Section
PLOS Computational Biology

BioJava Project Lead
-----------------------------------------------------------------------
