### ISSUE TITLE
Running tests modifies resources

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#39]
Running the tests modifies xml files in src/test/resources/jCE*. This is annoying for version control, but more importantly it could introduce dependencies between sequential test runs.

The files are being generated by `ProtodomainTest`. `ResourceList` seems to be providing a caching layer (generally a bad idea for unit tests), and uses `src/test/resources/<algorithm name> ` as the default output directory.

@dmyersturnbull, can you clarify the intent behind `ResourceList`? Is this needed for anything besides the diff methods?

At a minimum, the DEFAULT_DIR needs to be set to a temp directory and all the alignments calculated at each test run.

**Comment by lafita** [comment]
The current tests do not use resources, so I am closing this issue.
