### ISSUE TITLE
Add support for alignment of local files

### ISSUE THREAD

**Issue by andreasprlic** [rcsb/symmetry#41]
The current command line interface does not allow to run CE-symm for local PDB files. Add a command line option for that.

**Comment by lafita** [comment]
Symmetry analysis of local files can be now done through the Symmetry-GUI, the same way as for the other structural alignment algorithms (AlignmentGUI). 

CeSymm implements the StructuralAlignment inteface, so the CLI options should be the same as for the other structural alignments. Should we close this?
