### ISSUE TITLE
CESymmParameters: delete maxNrAlternatives?

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry#47]
This parameter is only used in the CeSymm.align method to set the number of iterations that the alignment loop should do (blacking out the previous alignment and doing another iteratively), given that the symmetry order of the protein was known. Was this parameter solely for this purpose, or does it have other functions/meanings? 

If the maxNrAlternatives is only setting the number of iterations could be deleted, because now the iteration loop is stopped when the TM score and the length of the last alignment drop significantly. With this approach the order of symmetry and thus the number of iterations is set at once, and the parameter is not used anymore.

Furthermore, another parameter could be introduced to CESymmParameters (named i.e. refineMethod), that specifies the refinement strategy: either the classical strategy with only one alignment or the new one with multiple alignments blacking out iteratively.

**Comment by sbliven** [comment]
My problem with the parameter is that 'maxNrAlternatives' sounds like it should implement alternative alignments, which aren't well supported by the current `align()->AFPChain` interface of StructureAlignment. Do we want to write it in such a way that CESymm can return multiple alternate alignments, or is it really just controlling some internal detail of the refinement protocol?

**Comment by lafita** [comment]
The parameter was renamed to maxSymmOrder (maximum order of symmetry) and continues to control the maximum number of successive alternative alignments that the CeSymm.align() method can perform in the MULTIPLE refiner option. 

For the other refinement options it can be used in the order detection methods, as a higher boundary for the order.

The parameter is now exposed to the user GUI (the SymmetryGUI), but it is not clear yet its usability (maybe if the user wants to see the possible lower orders of symmetry, i.e. the 2-fold symmetry in an 8-fold symmetric protein).
