### ISSUE TITLE
Use random seed by default in optimization

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#66]
The seed is initialized to 0 by default. A better default seed would be the current time or something. It should be random unless the user specifies it.

Also, setting a seed in the gui seems to hang during the alignment.

**Comment by lafita** [comment]
@sbliven can you give me a test case for the alignment hanging when the seed is changed? I cannot reproduce the bug.

I have set the default **random seed** to the last 6 digits of the *System.currentTimeMillis()* variable. That way it will change every time the user calls CE-Symm unless specified.

**Comment by lafita** [comment]
See [commit](https://github.com/biojava/biojava/commit/c0b629451f6040411832d23849ff67c5df0fa502) changes in biojava.
