### ISSUE TITLE
CE-Symm returns empty alignment for short proteins

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#68]
This can be indirectly reproduced by running CE-Symm on d2iolb_ from [a34b1bb](https://github.com/biojava/biojava/commit/a34b1bb2bdbcadc2b579fd5a2a16d526ef2224da) (before the length check was introduced in [d7133ca2](https://github.com/biojava/biojava/commit/d7133ca2db08d96f99eec3b25f04f8d85de738b1)). It will produce a out of bounds error after iterating down to the minimum subunit.

**Comment by lafita** [comment]
As a clue, it happens somewhere during the **optimization** of the alignment, because the parameter *minSubunitLen* is only used in this step and turning optimization OFF does not generate the Exception.

**Comment by lafita** [comment]
Fixed in [d365f3f](https://github.com/biojava/biojava/commit/d365f3f5763bc15d1130f0dd80411e63dec1cb32). The bug was solved by allowing missing information in AFPChain when CeSymm cannot find a meaningful alignment and returns an empty array.
