### ISSUE TITLE
Parameter GUI not updated between runs

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#69]
Every time you open the parameter GUI, the parameters displayed reset to the defaults. It would be much better for the GUI window to show the currently set parameters so that single parameters can be changed reliably.

**Comment by lafita** [comment]
Fixed in last biojava commit (see [here](https://github.com/biojava/biojava/commit/d47d7d2306a09a63ab7cf87ce7fcf57b88e89e63)).
