### ISSUE TITLE
Smarter window titles

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#70]
CE-Symm windows have overly redundant titles, like '1vym 1vym 1vym 1vym 1vym 1vym'. This is due to internally treating it as a multiple alignment, but it looks rather bad. Also, it hides the second part where the custom parameters are notated, which can be useful when looking at multiple alignments of the same structure.

**Comment by lafita** [comment]
This is fixed now! The title includes cesymm version, output and parameters used, although it is sometimes too large to fit in the window title. We discussed an option in the symmetry menu that prints this information instead of being in the title, but that should be in another issue.
