### ISSUE TITLE
Increase Java memory

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry#94]
At the moment in the **runCESymm.sh** script the Java memory is limited to 500 Mb, which seems very low to analyze structures:

`java -Xmx500M -jar "$DIR/cesymm-2.0.0-RC3.jar" "$@"`

We need to increase this to at least 2Gb, I would say.

**Comment by sbliven** [comment]
+1. It's max size, so it won't necessarily need this much for small cases.
