### ISSUE TITLE
Support Java 9+

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#97]
CE-Symm should support Java 9-11.

This could be accomplished by moving to biojava 5. See biojava/biojava#804

**Comment by sbliven** [comment]
Note that this will break backwards compatibility with Java 8. Would that require bumping the version to 3.0.0? That's a bit unfortunate since we're currently trying to publish v2.0.0.

**Comment by josemduarte** [comment]
In my understanding, it should not break backwards compatibility with java 8. That's what we did in biojava/biojava#804

**Comment by sbliven** [comment]
Brilliant. I'm not sure where I got that impression from. v2.1.0
